# Generated by Django 5.1.5 on 2025-05-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_level',
            field=models.CharField(blank=True, choices=[('m1', '1ère maternelle'), ('m2', '2ème maternelle'), ('m3', '3ème maternelle'), ('p1', '1ère primaire'), ('p2', '2ème primaire'), ('p3', '3ème primaire'), ('p4', '4ème primaire'), ('p5', '5ème primaire'), ('p6', '6ème primaire'), ('p7', '7ème primaire'), ('p8', '8ème primaire'), ('s1', '1ère secondaire'), ('s2', '2ème secondaire'), ('s3', '3ème secondaire'), ('s4', '4ème secondaire')], max_length=3),
        ),
    ]
