# Generated by Django 5.1.5 on 2025-05-31 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0002_alter_student_class_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_level',
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.schoolclass'),
        ),
    ]
