# Generated by Django 5.1.5 on 2025-06-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('temp_exclusion', 'Temporary Exclusion'), ('perm_exclusion', 'Permanent Exclusion'), ('fees_exclusion', 'Exclusion for Non‐payment'), ('internal_exclusion', 'Internal/Class Exclusion')], default='present', max_length=20)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to='teachers.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
            options={
                'ordering': ['-date', 'student__last_name', 'student__first_name'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
