# Generated by Django 5.1.5 on 2025-06-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('sick', 'Sick'), ('late', 'Late'), ('temp_exclusion', 'Temporary Exclusion'), ('perm_exclusion', 'Permanent Exclusion'), ('fees_exclusion', 'Exclusion for Non‐payment'), ('internal_exclusion', 'Internal/Class Exclusion')], default='present', max_length=20),
        ),
    ]
